---
abstract: 'Perl interface to GialloZafferano.it website to find cooking recipes'
author:
  - 'mudler <mudler@dark-lab.net>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build::Tiny: 0.034
  perl: 5.008005
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-GialloZafferano
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Encode: 0
  List::Util: 0
  Mojo::Base: 0
  Mojo::DOM: 0
  Mojo::UserAgent: 0
  feature: 0
  perl: 5.008_005
resources:
  bugtracker: https://github.com/mudler/WebService-GialloZafferano/issues
  homepage: https://github.com/mudler/WebService-GialloZafferano
  repository: https://github.com/mudler/WebService-GialloZafferano.git
version: 0.02
